// Auto-generated by generate_data.py — do not edit manually
const TIMELINE_DATA = {
  "repos": [
    {
      "name": "micromouse",
      "label": "Micromouse",
      "color": "#818cf8",
      "commits": [
        {
          "hash": "d6b86efe",
          "date": "2026-05-20T14:20:25",
          "author": "Bananasmoothii",
          "message": "yeah wall following still",
          "merged": false,
          "mine": true
        },
        {
          "hash": "d3d0aee3",
          "date": "2026-05-20T12:59:31",
          "author": "Bananasmoothii",
          "message": "Fix I2C sensor polling with round-robin",
          "merged": false,
          "mine": true
        },
        {
          "hash": "f2bcface",
          "date": "2026-05-19T21:10:22",
          "author": "Bananasmoothii",
          "message": "WALL FOLLOWING WORKS",
          "merged": false,
          "mine": true
        },
        {
          "hash": "03ad3938",
          "date": "2026-05-19T20:35:21",
          "author": "Bananasmoothii",
          "message": "Improve wall steering",
          "merged": false,
          "mine": true
        },
        {
          "hash": "a7a73d95",
          "date": "2026-05-18T19:12:09",
          "author": "Bananasmoothii",
          "message": "Fix wall steering",
          "merged": false,
          "mine": true
        },
        {
          "hash": "a1196c10",
          "date": "2026-05-18T15:22:45",
          "author": "Bananasmoothii",
          "message": "rewrite start",
          "merged": false,
          "mine": true
        },
        {
          "hash": "53b8b586",
          "date": "2026-05-18T13:48:47",
          "author": "Bananasmoothii",
          "message": "restart wall folowing from scratch",
          "merged": false,
          "mine": true
        },
        {
          "hash": "3efbef30",
          "date": "2026-05-18T10:12:34",
          "author": "Bananasmoothii",
          "message": "removed interrupts",
          "merged": false,
          "mine": true
        },
        {
          "hash": "b12bb887",
          "date": "2026-05-18T10:06:25",
          "author": "Bananasmoothii",
          "message": "removed more files",
          "merged": false,
          "mine": true
        },
        {
          "hash": "56b96b75",
          "date": "2026-05-18T10:03:09",
          "author": "Bananasmoothii",
          "message": "Removed all unnecessary code for minimal example of embassy-stm32 optimization issue",
          "merged": false,
          "mine": true
        },
        {
          "hash": "593da264",
          "date": "2026-05-18T09:41:45",
          "author": "Bananasmoothii",
          "message": "Meh-working DistanceToFrontWall",
          "merged": false,
          "mine": true
        },
        {
          "hash": "685b2ba5",
          "date": "2026-05-18T09:40:10",
          "author": "Bananasmoothii",
          "message": "Things",
          "merged": true,
          "mine": true
        },
        {
          "hash": "bb89702c",
          "date": "2026-05-17T13:31:37",
          "author": "Bananasmoothii",
          "message": "Cleanup",
          "merged": true,
          "mine": true
        },
        {
          "hash": "23d6b11a",
          "date": "2026-05-17T13:12:46",
          "author": "Bananasmoothii",
          "message": "Wall-following + distance sensor calibration",
          "merged": true,
          "mine": true
        },
        {
          "hash": "83d202a9",
          "date": "2026-05-16T23:30:26",
          "author": "Bananasmoothii",
          "message": "fix release mode with opt-level=1 on embassy-stm32 crate",
          "merged": true,
          "mine": true
        },
        {
          "hash": "7c121db9",
          "date": "2026-05-16T19:16:16",
          "author": "Bananasmoothii",
          "message": "reenable distance sensors",
          "merged": true,
          "mine": true
        },
        {
          "hash": "41bcf4c2",
          "date": "2026-05-16T19:15:30",
          "author": "Bananasmoothii",
          "message": "reenable distance sensors",
          "merged": true,
          "mine": true
        },
        {
          "hash": "36f02adf",
          "date": "2026-05-16T19:04:01",
          "author": "Bananasmoothii",
          "message": "tweak",
          "merged": true,
          "mine": true
        },
        {
          "hash": "5520a858",
          "date": "2026-05-16T17:35:48",
          "author": "Bananasmoothii",
          "message": "OVERSHOOOT",
          "merged": true,
          "mine": true
        },
        {
          "hash": "4ab1479c",
          "date": "2026-05-16T00:48:28",
          "author": "Bananasmoothii",
          "message": "  Pivot turn: dyn TrajectorySegment, velocity-dependent motor cutoff",
          "merged": true,
          "mine": true
        },
        {
          "hash": "1679f418",
          "date": "2026-05-15T17:16:47",
          "author": "Bananasmoothii",
          "message": "Documentation about the true identity of what the hell we are doing here",
          "merged": true,
          "mine": true
        },
        {
          "hash": "e33c5914",
          "date": "2026-05-15T16:43:02",
          "author": "Bananasmoothii",
          "message": "Straight-line accuracy: pulse-width debounce, heading PI steering, tick-based stop",
          "merged": true,
          "mine": true
        },
        {
          "hash": "ba7cd541",
          "date": "2026-05-14T17:00:13",
          "author": "Bananasmoothii",
          "message": "Code cleanup, change velocity calculation to dx/dt instead of counting tick",
          "merged": true,
          "mine": true
        },
        {
          "hash": "ac7fd873",
          "date": "2026-05-14T15:33:26",
          "author": "Bananasmoothii",
          "message": "Fix hall sensor tick count at medium - high speed, continue trying to find the correct PI constants along with PWM_TO_SPEED_FACTOR",
          "merged": true,
          "mine": true
        },
        {
          "hash": "08b9bfc6",
          "date": "2026-05-13T23:24:34",
          "author": "Bananasmoothii",
          "message": "add flash_log.rs, use one flash sector for log",
          "merged": true,
          "mine": true
        },
        {
          "hash": "0b604f28",
          "date": "2026-05-13T22:38:37",
          "author": "Bananasmoothii",
          "message": "tweak start",
          "merged": true,
          "mine": true
        },
        {
          "hash": "712da495",
          "date": "2026-05-13T22:11:19",
          "author": "Bananasmoothii",
          "message": "simplify, make speed to PWM depend on battery voltage",
          "merged": true,
          "mine": true
        },
        {
          "hash": "2a082432",
          "date": "2026-05-13T15:54:25",
          "author": "Bananasmoothii",
          "message": "debug",
          "merged": true,
          "mine": true
        },
        {
          "hash": "5b768a6d",
          "date": "2026-05-08T20:00:51",
          "author": "Bananasmoothii",
          "message": "logs and things, need wheels to continue",
          "merged": true,
          "mine": true
        },
        {
          "hash": "147566f1",
          "date": "2026-05-08T19:08:07",
          "author": "Bananasmoothii",
          "message": "Straight line seems done",
          "merged": true,
          "mine": true
        },
        {
          "hash": "4a1b3831",
          "date": "2026-05-07T19:04:54",
          "author": "Bananasmoothii",
          "message": "Refactoring & cleaning of hall sensor + MPU, add docs for Kalman filter constants",
          "merged": true,
          "mine": true
        },
        {
          "hash": "c99dd8ee",
          "date": "2026-05-07T16:50:34",
          "author": "Bananasmoothii",
          "message": "wipe everything",
          "merged": true,
          "mine": true
        },
        {
          "hash": "45b5d9cc",
          "date": "2026-04-29T00:28:09",
          "author": "Bananasmoothii",
          "message": "smoother trajectory",
          "merged": true,
          "mine": true
        },
        {
          "hash": "4dd68687",
          "date": "2026-04-28T23:59:19",
          "author": "Bananasmoothii",
          "message": "fix velocity calculations better",
          "merged": true,
          "mine": true
        },
        {
          "hash": "69c4b8ef",
          "date": "2026-04-28T22:11:14",
          "author": "Bananasmoothii",
          "message": "fix velocity calculations",
          "merged": true,
          "mine": true
        },
        {
          "hash": "71acb38b",
          "date": "2026-04-28T21:05:05",
          "author": "Bananasmoothii",
          "message": "fix odometry",
          "merged": true,
          "mine": true
        },
        {
          "hash": "0b5ef071",
          "date": "2026-04-28T15:36:27",
          "author": "Bananasmoothii",
          "message": "AI things",
          "merged": true,
          "mine": true
        },
        {
          "hash": "451dc8df",
          "date": "2026-04-28T14:24:37",
          "author": "Bananasmoothii",
          "message": "fix distance sensors again (apparently some pins don't work)",
          "merged": true,
          "mine": true
        },
        {
          "hash": "6cb1369f",
          "date": "2026-04-28T13:24:23",
          "author": "Bananasmoothii",
          "message": "Fix merge, add things",
          "merged": true,
          "mine": true
        },
        {
          "hash": "48b737f8",
          "date": "2026-04-28T10:59:35",
          "author": "Bananasmoothii",
          "message": "Merge branch 'refs/heads/positionning' into trajectory",
          "merged": true,
          "mine": true
        },
        {
          "hash": "2b8835ee",
          "date": "2026-04-26T19:20:30",
          "author": "Bananasmoothii",
          "message": "tweak buzzer",
          "merged": true,
          "mine": true
        },
        {
          "hash": "e92b1dd4",
          "date": "2026-04-26T19:08:07",
          "author": "Bananasmoothii",
          "message": "ALL SENSORS WORK",
          "merged": true,
          "mine": true
        },
        {
          "hash": "f7a186ab",
          "date": "2026-04-26T18:40:26",
          "author": "Bananasmoothii",
          "message": "use n.hz()",
          "merged": true,
          "mine": true
        },
        {
          "hash": "041b269b",
          "date": "2026-04-26T18:38:38",
          "author": "Bananasmoothii",
          "message": "FIXED I2C RECOVERY I LOVE CLAUDE",
          "merged": true,
          "mine": true
        },
        {
          "hash": "b8e58d8e",
          "date": "2026-04-26T17:36:51",
          "author": "Bananasmoothii",
          "message": "tried to make an I2C recovery system",
          "merged": true,
          "mine": true
        },
        {
          "hash": "7064ccbc",
          "date": "2026-04-26T15:54:49",
          "author": "Bananasmoothii",
          "message": "work on vl53l1x sensors",
          "merged": true,
          "mine": true
        },
        {
          "hash": "bba55cc7",
          "date": "2026-04-25T19:26:16",
          "author": "Bananasmoothii",
          "message": "buzzer tweaked",
          "merged": true,
          "mine": true
        },
        {
          "hash": "028353f7",
          "date": "2026-04-25T19:11:50",
          "author": "Bananasmoothii",
          "message": "buzzer works",
          "merged": true,
          "mine": true
        },
        {
          "hash": "82ab2148",
          "date": "2026-04-23T21:55:00",
          "author": "Bananasmoothii",
          "message": "revert wrongly reported unused",
          "merged": true,
          "mine": true
        },
        {
          "hash": "1fd1732d",
          "date": "2026-04-23T21:47:40",
          "author": "Bananasmoothii",
          "message": "trajectory optimisation",
          "merged": true,
          "mine": true
        },
        {
          "hash": "b598e998",
          "date": "2026-04-23T18:11:30",
          "author": "Bananasmoothii",
          "message": "research.md",
          "merged": true,
          "mine": true
        },
        {
          "hash": "f5ed69ae",
          "date": "2026-04-23T16:56:29",
          "author": "Bananasmoothii",
          "message": "vibe code trajectory",
          "merged": true,
          "mine": true
        },
        {
          "hash": "46702d3d",
          "date": "2026-04-23T16:25:36",
          "author": "Bananasmoothii",
          "message": "Merge branch 'refs/heads/master' into trajectory",
          "merged": true,
          "mine": true
        },
        {
          "hash": "015e5c40",
          "date": "2026-04-23T15:52:29",
          "author": "Bananasmoothii",
          "message": "refactor to right folder",
          "merged": true,
          "mine": true
        },
        {
          "hash": "b875895e",
          "date": "2026-04-23T13:30:09",
          "author": "Bananasmoothii",
          "message": "add dual-motor overcurrent protection and fault handling formatting",
          "merged": true,
          "mine": true
        },
        {
          "hash": "a91d8279",
          "date": "2026-04-22T16:49:01",
          "author": "lumin0u",
          "message": "fix no lab",
          "merged": true,
          "mine": false
        },
        {
          "hash": "a2529ef5",
          "date": "2026-04-22T16:48:20",
          "author": "lumin0u",
          "message": "started trajectory",
          "merged": true,
          "mine": false
        },
        {
          "hash": "686cc932",
          "date": "2026-04-22T14:15:38",
          "author": "lumin0u",
          "message": "added labyrinth.rs",
          "merged": true,
          "mine": false
        },
        {
          "hash": "b7763ec4",
          "date": "2026-04-21T17:55:50",
          "author": "Bananasmoothii",
          "message": "vibe-code Refactor odometry and motor control using atomic variables for tick tracking",
          "merged": true,
          "mine": true
        },
        {
          "hash": "70afb630",
          "date": "2026-04-18T18:28:10",
          "author": "Bananasmoothii",
          "message": "refactoring & corrections",
          "merged": true,
          "mine": true
        },
        {
          "hash": "e629d9a7",
          "date": "2026-04-18T14:45:45",
          "author": "Bananasmoothii",
          "message": "refactoring & documentation",
          "merged": true,
          "mine": true
        },
        {
          "hash": "6743fd28",
          "date": "2026-04-18T13:33:49",
          "author": "Bananasmoothii",
          "message": "format",
          "merged": true,
          "mine": true
        },
        {
          "hash": "fdb22adf",
          "date": "2026-04-18T01:21:30",
          "author": "Bananasmoothii",
          "message": "Refactor positioning with channel-based tasks and Kalman filters - Migrate to a channel-based positioning task architecture - Implement 1D Kalman filter for orientation (including compass) - Implement 2D Kalman filter using accelerometer data to compensate for low-resolution odometry - Add architectural documentation - Resolve formatting warnings",
          "merged": true,
          "mine": true
        },
        {
          "hash": "1eac7dc5",
          "date": "2026-04-18T00:02:36",
          "author": "Bananasmoothii",
          "message": "Vibe-coded odometry and mpu positioning",
          "merged": true,
          "mine": true
        },
        {
          "hash": "3a4a025f",
          "date": "2026-04-17T19:47:09",
          "author": "Bananasmoothii",
          "message": "?",
          "merged": true,
          "mine": true
        },
        {
          "hash": "5869504d",
          "date": "2026-04-17T19:46:44",
          "author": "Bananasmoothii",
          "message": "PCB !! (open with KiCad) / produce with pcb.zip, bom.csv & positions.csv",
          "merged": true,
          "mine": true
        },
        {
          "hash": "e2346007",
          "date": "2026-04-17T19:43:54",
          "author": "Bananasmoothii",
          "message": "add hall sensor continuous measuring functionality",
          "merged": true,
          "mine": true
        },
        {
          "hash": "dcdd7977",
          "date": "2026-03-13T20:13:04",
          "author": "Bananasmoothii",
          "message": "motor works",
          "merged": true,
          "mine": true
        },
        {
          "hash": "b3481b9b",
          "date": "2026-03-12T18:48:33",
          "author": "Bananasmoothii",
          "message": "refactor, display cell voltages",
          "merged": true,
          "mine": true
        },
        {
          "hash": "043b93fe",
          "date": "2026-03-12T16:18:23",
          "author": "Bananasmoothii",
          "message": "refactor, start working on motors (after 63h of project yay)",
          "merged": true,
          "mine": true
        },
        {
          "hash": "182e26cd",
          "date": "2026-03-11T12:29:39",
          "author": "Bananasmoothii",
          "message": "cleanup",
          "merged": true,
          "mine": true
        },
        {
          "hash": "5a24d071",
          "date": "2026-03-11T11:30:04",
          "author": "Bananasmoothii",
          "message": "Revert \"nothing works anymore yay\"",
          "merged": true,
          "mine": true
        },
        {
          "hash": "37cf85aa",
          "date": "2026-03-11T11:01:20",
          "author": "Bananasmoothii",
          "message": "nothing works anymore yay",
          "merged": true,
          "mine": true
        },
        {
          "hash": "2d8e2017",
          "date": "2026-03-11T10:01:38",
          "author": "Bananasmoothii",
          "message": "debugging",
          "merged": true,
          "mine": true
        },
        {
          "hash": "19779f1a",
          "date": "2026-03-04T16:44:18",
          "author": "Bananasmoothii",
          "message": "f",
          "merged": true,
          "mine": true
        },
        {
          "hash": "a2e95d64",
          "date": "2026-03-04T16:43:59",
          "author": "Bananasmoothii",
          "message": "mpu works, simplified vl53l1x driver wrapper",
          "merged": true,
          "mine": true
        },
        {
          "hash": "8167ce07",
          "date": "2026-02-17T14:08:14",
          "author": "Bananasmoothii",
          "message": "refactor",
          "merged": true,
          "mine": true
        },
        {
          "hash": "71b993e8",
          "date": "2026-02-15T11:19:59",
          "author": "Bananasmoothii",
          "message": "don't report phase fails",
          "merged": true,
          "mine": true
        },
        {
          "hash": "12e1c619",
          "date": "2026-02-15T10:59:07",
          "author": "Bananasmoothii",
          "message": "two sensors",
          "merged": true,
          "mine": true
        },
        {
          "hash": "218bf86c",
          "date": "2026-02-13T08:59:54",
          "author": "Bananasmoothii",
          "message": "update cargo, *",
          "merged": true,
          "mine": true
        },
        {
          "hash": "d926b588",
          "date": "2026-02-12T19:36:46",
          "author": "Bananasmoothii",
          "message": "cleanup",
          "merged": true,
          "mine": true
        },
        {
          "hash": "00a87b67",
          "date": "2026-02-12T19:35:14",
          "author": "Bananasmoothii",
          "message": "lots of fixes",
          "merged": true,
          "mine": true
        },
        {
          "hash": "8ee20c53",
          "date": "2026-02-12T18:02:35",
          "author": "Bananasmoothii",
          "message": "fix everything back",
          "merged": true,
          "mine": true
        },
        {
          "hash": "0fa4162c",
          "date": "2026-02-12T16:50:08",
          "author": "Bananasmoothii",
          "message": "try using async vl53l0x",
          "merged": false,
          "mine": true
        },
        {
          "hash": "8e31094c",
          "date": "2026-02-09T15:09:05",
          "author": "Bananasmoothii",
          "message": "?",
          "merged": true,
          "mine": true
        },
        {
          "hash": "1150a3c0",
          "date": "2026-02-09T15:08:37",
          "author": "Bananasmoothii",
          "message": "update dependencies to use my fork",
          "merged": true,
          "mine": true
        },
        {
          "hash": "af2730ca",
          "date": "2026-02-09T13:17:08",
          "author": "Bananasmoothii",
          "message": "temp",
          "merged": true,
          "mine": true
        },
        {
          "hash": "a4f427ed",
          "date": "2026-02-02T21:07:45",
          "author": "Bananasmoothii",
          "message": "fix interrupt deadlock",
          "merged": true,
          "mine": true
        },
        {
          "hash": "b29d6974",
          "date": "2026-02-02T20:54:12",
          "author": "Bananasmoothii",
          "message": "forgot to spawn task",
          "merged": true,
          "mine": true
        },
        {
          "hash": "3b1c6f5b",
          "date": "2026-02-02T20:37:52",
          "author": "Bananasmoothii",
          "message": "tried to use vl53l0x",
          "merged": true,
          "mine": true
        },
        {
          "hash": "44e7eef5",
          "date": "2026-02-02T18:56:38",
          "author": "Bananasmoothii",
          "message": "more cleanup x2",
          "merged": true,
          "mine": true
        },
        {
          "hash": "93c71d8e",
          "date": "2026-02-02T18:52:14",
          "author": "Bananasmoothii",
          "message": "more cleanup",
          "merged": true,
          "mine": true
        },
        {
          "hash": "a7c9c927",
          "date": "2026-02-02T18:51:09",
          "author": "Bananasmoothii",
          "message": "cleanup",
          "merged": true,
          "mine": true
        },
        {
          "hash": "cd7277ef",
          "date": "2026-02-02T18:43:50",
          "author": "Bananasmoothii",
          "message": "end refactor",
          "merged": true,
          "mine": true
        },
        {
          "hash": "ac5a92a2",
          "date": "2026-02-02T18:43:33",
          "author": "Bananasmoothii",
          "message": "end refactor",
          "merged": true,
          "mine": true
        },
        {
          "hash": "0d8f1236",
          "date": "2026-02-02T17:07:52",
          "author": "Bananasmoothii",
          "message": "refactor",
          "merged": true,
          "mine": true
        },
        {
          "hash": "2ead45b2",
          "date": "2026-02-02T11:38:57",
          "author": "Bananasmoothii",
          "message": "small things",
          "merged": true,
          "mine": true
        },
        {
          "hash": "84ee72e5",
          "date": "2026-02-01T23:47:18",
          "author": "Bananasmoothii",
          "message": "re-add button",
          "merged": true,
          "mine": true
        },
        {
          "hash": "e323840c",
          "date": "2026-02-01T23:44:17",
          "author": "Bananasmoothii",
          "message": "make it more robust",
          "merged": true,
          "mine": true
        },
        {
          "hash": "21c39328",
          "date": "2026-02-01T22:26:21",
          "author": "Bananasmoothii",
          "message": "refactor, better prints",
          "merged": true,
          "mine": true
        },
        {
          "hash": "4276f042",
          "date": "2026-02-01T21:52:28",
          "author": "Bananasmoothii",
          "message": "cleanup, use interrupts",
          "merged": true,
          "mine": true
        },
        {
          "hash": "2bce45bd",
          "date": "2026-02-01T19:48:21",
          "author": "Bananasmoothii",
          "message": "IT FUCKING WORKS",
          "merged": true,
          "mine": true
        },
        {
          "hash": "c5b3542f",
          "date": "2026-02-01T18:50:22",
          "author": "Bananasmoothii",
          "message": "dtn",
          "merged": true,
          "mine": true
        },
        {
          "hash": "0b9273bf",
          "date": "2026-01-30T17:55:05",
          "author": "Bananasmoothii",
          "message": "sfhn",
          "merged": true,
          "mine": true
        },
        {
          "hash": "619608ac",
          "date": "2026-01-29T18:48:10",
          "author": "Bananasmoothii",
          "message": "DEBUG.md",
          "merged": true,
          "mine": true
        },
        {
          "hash": "1f0817ef",
          "date": "2026-01-29T18:14:28",
          "author": "Bananasmoothii",
          "message": "gitignore",
          "merged": true,
          "mine": true
        },
        {
          "hash": "c8b70a0e",
          "date": "2026-01-29T18:13:30",
          "author": "Bananasmoothii",
          "message": "srjstrh",
          "merged": true,
          "mine": true
        }
      ]
    },
    {
      "name": "vl53l0x",
      "label": "VL53L0X driver",
      "color": "#fb923c",
      "commits": [
        {
          "hash": "afb05560",
          "date": "2026-03-03T18:42:42",
          "author": "Bananasmoothii",
          "message": "make i2c public (useful for manual resets in somewhat sketchy code)",
          "merged": true,
          "mine": true
        },
        {
          "hash": "042f41d7",
          "date": "2026-02-13T08:49:48",
          "author": "Bananasmoothii",
          "message": "Don't report SigmaFail anymore (requires more computations)",
          "merged": true,
          "mine": true
        },
        {
          "hash": "84a0caea",
          "date": "2026-02-12T18:27:59",
          "author": "Bananasmoothii",
          "message": "add defmt to RangeStatus",
          "merged": true,
          "mine": true
        },
        {
          "hash": "890ecb25",
          "date": "2026-02-12T18:26:25",
          "author": "Bananasmoothii",
          "message": "Merge pull request #1 from Induct-ie/master",
          "merged": true,
          "mine": true
        },
        {
          "hash": "21dffc1b",
          "date": "2026-02-12T18:20:51",
          "author": "Bananasmoothii",
          "message": "add defmt as optional dependency",
          "merged": true,
          "mine": true
        },
        {
          "hash": "266992e9",
          "date": "2026-02-09T13:01:08",
          "author": "Bananasmoothii",
          "message": ".gitignore",
          "merged": true,
          "mine": true
        },
        {
          "hash": "5771ec99",
          "date": "2026-02-12T18:15:11",
          "author": "Bananasmoothii",
          "message": "idk",
          "merged": false,
          "mine": true
        },
        {
          "hash": "077871c6",
          "date": "2026-02-09T20:54:28",
          "author": "Bananasmoothii",
          "message": "bump minor version",
          "merged": false,
          "mine": true
        },
        {
          "hash": "a685ded1",
          "date": "2026-02-09T20:53:16",
          "author": "Bananasmoothii",
          "message": "add defmt as optional dependency",
          "merged": false,
          "mine": true
        },
        {
          "hash": "7e09be31",
          "date": "2026-02-09T13:18:24",
          "author": "Bananasmoothii",
          "message": "Refactor in multiple files",
          "merged": false,
          "mine": true
        },
        {
          "hash": "6117cb66",
          "date": "2026-02-09T13:01:08",
          "author": "Bananasmoothii",
          "message": ".gitignore",
          "merged": false,
          "mine": true
        },
        {
          "hash": "3f402020",
          "date": "2026-02-09T13:00:29",
          "author": "Bananasmoothii",
          "message": "simplify code and add a feature for async i2c (from embassy-hal-async)",
          "merged": false,
          "mine": true
        },
        {
          "hash": "fcbdbd6b",
          "date": "2026-02-09T12:18:58",
          "author": "Bananasmoothii",
          "message": "refactor VL53L0x driver to support async I2C operations and add embassy-sync dependency",
          "merged": false,
          "mine": true
        }
      ]
    },
    {
      "name": "vl53l1",
      "label": "VL53L1X driver",
      "color": "#34d399",
      "commits": [
        {
          "hash": "b05ac70d",
          "date": "2026-04-26T13:11:07",
          "author": "Bananasmoothii",
          "message": "support changing i2c address: bump version",
          "merged": false,
          "mine": true
        },
        {
          "hash": "3e4089b0",
          "date": "2026-04-26T13:08:01",
          "author": "Bananasmoothii",
          "message": "Keep stat_nvm in sync so init_and_start_range doesn't overwrite the register back to the old address.",
          "merged": false,
          "mine": true
        },
        {
          "hash": "c98772d2",
          "date": "2026-04-26T12:06:39",
          "author": "Bananasmoothii",
          "message": "Make address changeable",
          "merged": false,
          "mine": true
        },
        {
          "hash": "634f0077",
          "date": "2026-02-12T18:41:12",
          "author": "Bananasmoothii",
          "message": "cargo, gitignore",
          "merged": true,
          "mine": true
        },
        {
          "hash": "253b86d0",
          "date": "2026-02-12T18:36:07",
          "author": "Bananasmoothii",
          "message": "comments",
          "merged": true,
          "mine": true
        },
        {
          "hash": "cde5c833",
          "date": "2026-02-12T18:34:04",
          "author": "Bananasmoothii",
          "message": "try to add async everywhere",
          "merged": false,
          "mine": true
        },
        {
          "hash": "b46f6bc8",
          "date": "2026-02-01T23:44:10",
          "author": "Bananasmoothii",
          "message": "make it more robust",
          "merged": true,
          "mine": true
        },
        {
          "hash": "30613ac3",
          "date": "2026-02-01T21:35:42",
          "author": "Bananasmoothii",
          "message": "make defmt optional",
          "merged": true,
          "mine": true
        },
        {
          "hash": "87a1548b",
          "date": "2026-02-01T21:35:07",
          "author": "Bananasmoothii",
          "message": "Add doc from https://www.st.com/resource/en/application_note/an5263-configuring-the-vl53l1x-timeofflight-sensor-to-range-up-to-100-hz-stmicroelectronics.pdf",
          "merged": true,
          "mine": true
        },
        {
          "hash": "c4363791",
          "date": "2026-02-01T19:48:13",
          "author": "Bananasmoothii",
          "message": "IT WORKS",
          "merged": true,
          "mine": true
        }
      ]
    },
    {
      "name": "mpu9250",
      "label": "MPU9250 driver",
      "color": "#c084fc",
      "commits": [
        {
          "hash": "4bc31c80",
          "date": "2026-02-15T13:21:42",
          "author": "Bananasmoothii",
          "message": "add defmt support",
          "merged": false,
          "mine": true
        }
      ]
    }
  ],
  "media": [
    {
      "path": "media/image-1 20260409.png",
      "date": "2026-04-09T12:00:00",
      "type": "photo"
    },
    {
      "path": "media/image-2 20260413.png",
      "date": "2026-04-13T12:00:00",
      "type": "photo"
    },
    {
      "path": "media/image-3 20260413.png",
      "date": "2026-04-13T12:00:00",
      "type": "photo"
    },
    {
      "path": "media/image-4 20260413.png",
      "date": "2026-04-13T12:00:00",
      "type": "photo"
    },
    {
      "path": "media/original_095ffacd-d234-4622-89d0-3a2846f141bb_PXL_20260415_184908608.jpg",
      "date": "2026-04-15T18:49:08",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260126_161728861.jpg",
      "date": "2026-01-26T16:17:28",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260126_162100756.jpg",
      "date": "2026-01-26T16:21:00",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260202_200006607.jpg",
      "date": "2026-02-02T20:00:06",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260306_192910711.mp4",
      "date": "2026-03-06T19:29:10",
      "type": "video"
    },
    {
      "path": "media/PXL_20260310_105622443.mp4",
      "date": "2026-03-10T10:56:22",
      "type": "video"
    },
    {
      "path": "media/PXL_20260310_105911450.jpg",
      "date": "2026-03-10T10:59:11",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260310_111805629.jpg",
      "date": "2026-03-10T11:18:05",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260310_111900392.jpg",
      "date": "2026-03-10T11:19:00",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260311_213031688.jpg",
      "date": "2026-03-11T21:30:31",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260312_104955946~2.jpg",
      "date": "2026-03-12T10:49:55",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260313_160347243.mp4",
      "date": "2026-03-13T16:03:47",
      "type": "video"
    },
    {
      "path": "media/PXL_20260324_132449990.mp4",
      "date": "2026-03-24T13:24:49",
      "type": "video"
    },
    {
      "path": "media/PXL_20260324_145423954.mp4",
      "date": "2026-03-24T14:54:23",
      "type": "video"
    },
    {
      "path": "media/PXL_20260415_183648966.jpg",
      "date": "2026-04-15T18:36:48",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260416_174212369.jpg",
      "date": "2026-04-16T17:42:12",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260420_100110728.jpg",
      "date": "2026-04-20T10:01:10",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260420_140650980.jpg",
      "date": "2026-04-20T14:06:50",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260421_144436535.jpg",
      "date": "2026-04-21T14:44:36",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260421_151336662.jpg",
      "date": "2026-04-21T15:13:36",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260421_151529925.jpg",
      "date": "2026-04-21T15:15:29",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260421_162447418.mp4",
      "date": "2026-04-21T16:24:47",
      "type": "video"
    },
    {
      "path": "media/PXL_20260421_162544543.mp4",
      "date": "2026-04-21T16:25:44",
      "type": "video"
    },
    {
      "path": "media/PXL_20260422_084709006.jpg",
      "date": "2026-04-22T08:47:09",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260422_144235982.mp4",
      "date": "2026-04-22T14:42:35",
      "type": "video"
    },
    {
      "path": "media/PXL_20260423_191425751.jpg",
      "date": "2026-04-23T19:14:25",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260424_134002757.LOCKED.mp4",
      "date": "2026-04-24T13:40:02",
      "type": "video"
    },
    {
      "path": "media/PXL_20260424_134105569.LOCKED.mp4",
      "date": "2026-04-24T13:41:05",
      "type": "video"
    },
    {
      "path": "media/PXL_20260424_134156218.LOCKED.mp4",
      "date": "2026-04-24T13:41:56",
      "type": "video"
    },
    {
      "path": "media/PXL_20260424_143647409.jpg",
      "date": "2026-04-24T14:36:47",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260425_165336108.jpg",
      "date": "2026-04-25T16:53:36",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260425_172332223.mp4",
      "date": "2026-04-25T17:23:32",
      "type": "video"
    },
    {
      "path": "media/PXL_20260426_164857328.jpg",
      "date": "2026-04-26T16:48:57",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260426_164904233.jpg",
      "date": "2026-04-26T16:49:04",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260427_103816813.mp4",
      "date": "2026-04-27T10:38:16",
      "type": "video"
    },
    {
      "path": "media/PXL_20260427_103846362.mp4",
      "date": "2026-04-27T10:38:46",
      "type": "video"
    },
    {
      "path": "media/PXL_20260427_115904437.jpg",
      "date": "2026-04-27T11:59:04",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260427_203327881.mp4",
      "date": "2026-04-27T20:33:27",
      "type": "video"
    },
    {
      "path": "media/PXL_20260428_144506429.jpg",
      "date": "2026-04-28T14:45:06",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260428_155355750.mp4",
      "date": "2026-04-28T15:53:55",
      "type": "video"
    },
    {
      "path": "media/PXL_20260428_184047565.jpg",
      "date": "2026-04-28T18:40:47",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260428_204841753.mp4",
      "date": "2026-04-28T20:48:41",
      "type": "video"
    },
    {
      "path": "media/PXL_20260506_143035850.mp4",
      "date": "2026-05-06T14:30:35",
      "type": "video"
    },
    {
      "path": "media/PXL_20260507_133121331.jpg",
      "date": "2026-05-07T13:31:21",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260509_104550121.jpg",
      "date": "2026-05-09T10:45:50",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260509_105133438.jpg",
      "date": "2026-05-09T10:51:33",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260511_144912905.mp4",
      "date": "2026-05-11T14:49:12",
      "type": "video"
    },
    {
      "path": "media/PXL_20260512_104114566.jpg",
      "date": "2026-05-12T10:41:14",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260513_104502830.mp4",
      "date": "2026-05-13T10:45:02",
      "type": "video",
      "note": "10 min"
    },
    {
      "path": "media/PXL_20260513_105515019.mp4",
      "date": "2026-05-13T10:55:15",
      "type": "video",
      "note": "25 min"
    },
    {
      "path": "media/PXL_20260513_112239469.mp4",
      "date": "2026-05-13T11:22:39",
      "type": "video"
    },
    {
      "path": "media/PXL_20260513_112854837.mp4",
      "date": "2026-05-13T11:28:54",
      "type": "video"
    },
    {
      "path": "media/PXL_20260513_121200348.jpg",
      "date": "2026-05-13T12:12:00",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260514_143418286.jpg",
      "date": "2026-05-14T14:34:18",
      "type": "photo",
      "note": "Tourne à droite à cause de cette poussière qui bloque un peu les roues dentées"
    },
    {
      "path": "media/PXL_20260515_131641282.mp4",
      "date": "2026-05-15T13:16:41",
      "type": "video"
    },
    {
      "path": "media/PXL_20260515_134614214.jpg",
      "date": "2026-05-15T13:46:14",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260515_224931736.mp4",
      "date": "2026-05-15T22:49:31",
      "type": "video"
    },
    {
      "path": "media/PXL_20260516_121244516.jpg",
      "date": "2026-05-16T12:12:44",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260517_130954581.jpg",
      "date": "2026-05-17T13:09:54",
      "type": "photo"
    },
    {
      "path": "media/PXL_20260518_084833173.mp4",
      "date": "2026-05-18T08:48:33",
      "type": "video"
    }
  ]
};
