use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");

    // Copy our custom memory.x into OUT_DIR and add it to the linker search path.
    // This ensures the linker picks up our version (384 K FLASH + 128 K LOG reserved for
    // flash_log) instead of the one generated by embassy-stm32's memory-x feature.
    // let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    // fs::copy("memory.x", out.join("memory.x")).unwrap();
    // println!("cargo:rustc-link-search={}", out.display());
    // println!("cargo:rerun-if-changed=memory.x");
    // println!("cargo:rerun-if-changed=build.rs");
}
